manga1 = Item.create!(name: "One Piece Manga v.95 (Wano Country Arc)", type_tag: "manga", description: "The Ninja-Pirate-Mink-Samurai Alliance gather in Wano Country and prepare for the battle against the Beasts Pirates. The history of Kozuki Oden and his ties to Wano Country, Whitebeard and Gol D. Roger are revealed, and the Alliance assaults Onigashima to take down the allied forces of Kaido and Big Mom, all while alliances shift on all sides of the siege. Meanwhile, after the events during the recent Levely, the world goes through dramatic changes.", availability: true, price: 29.99)
manga1.photo.attach(io: File.open("/Users/johnangcla/Desktop/animezon_imgages/onepiece-manga.jpeg"), filename: 'onepiece-manga.jpeg')

manga2 = Item.create!(name: "Air Gear Manga v.37", type_tag: "manga", description: "Air Gear volume 37 features story and art by Oh!Great. The final battle for the fate of the world of the Air Trecks is underway, pitting Ikki and Ringo against Sora and Rika! It’s a white-knuckled, no-holds-barred race to the surface through the massive Tower of Trophaeum, and now that the best riders on the planet are finally facing off, victory will only come with great sacrifice. But when Sora reveals a stunning secret, Ikki realizes that the game has changed, and winning is more important than even he could have imagined…", availability: true, price: 19.99)
manga2.photo.attach(io: File.open("/Users/johnangcla/Desktop/animezon_imgages/air-gear-manga.jpeg"), filename: 'air-gear-manga.jpeg')

manga3 = Item.create!(name: "Bleach Manga v.74 (The final volume)", type_tag: "manga", description: "The final battle against Yhwach gets underway as Ichigo Kurosaki and his allies reach the Quincy King's throne room. Can Ichigo put an end to the thousand-year war between the Shinigami and Quincy? The emotional conclusion of Bleach is here!The final battle against Yhwach gets underway as Ichigo Kurosaki and his allies reach the Quincy King's throne room. Can Ichigo put an end to the thousand-year war between the Shinigami and Quincy? The emotional conclusion of Bleach is here!", availability: true, price: 24.99)
manga3.photo.attach(io: File.open("/Users/johnangcla/Desktop/animezon_imgages/bleach-manga.jpeg"), filename: 'bleach-manga.jpeg')

manga4 = Item.create!(name: "Kimetsu no Yaiba Manga v.1 (Demon Slayer the first volume)", type_tag: "manga", description: "In Taisho-era Japan, Kamado Tanjiro is a kindhearted boy who makes a living selling charcoal. But his peaceful life is shattered when a demon slaughters his entire family. ... Learning to slay demons won't be easy, and Tanjiro barely knows where to start.", availability: true, price: 14.99)
manga4.photo.attach(io: File.open("/Users/johnangcla/Desktop/animezon_imgages/ds-manga.jpeg"), filename: 'ds-manga.jpeg')

manga5 = Item.create!(name: "Boku no Hero Academia Manga v.28 (My Hero Academia)", type_tag: "manga", description: "Mirko desperately battles High-Ends in order to reach Tomura's stasis tank, knowing exactly how much is at stake if she fails. At the PLF hideout, Dabi is determined to roast Hawks, but Tokoyami isn't about to let his mentor fall.", availability: true, price: 23.99)
manga5.photo.attach(io: File.open("/Users/johnangcla/Desktop/animezon_imgages/hero-manga.jpeg"), filename: 'hero-manga.jpeg')

manga6 = Item.create!(name: "Hunter x Hunter Manga v.17", type_tag: "manga", description: "In an unexpected turn of events, Gon, Killua, and their sometime enemy Hisoka pull off a stunning victory in a heated game of deadly dodge ball, working together to defeat Razor and his 14 Devils.", availability: true, price: 19.99)
manga6.photo.attach(io: File.open("/Users/johnangcla/Desktop/animezon_imgages/hunter-manga.jpg"), filename: 'hunter-manga.jpg')

manga7 = Item.create!(name: "Jujutsu Kaisen Manga v.14", type_tag: "manga", description: "While Sukuna, who has been temporarily unleashed, is wrecking Shibuya, Fushiguro suffers a serious injury from a curse user who caught him unawares.", availability: true, price: 14.99)
manga7.photo.attach(io: File.open("/Users/johnangcla/Desktop/animezon_imgages/jujutsu-manga.png"), filename: 'jujutsu-manga.png')

manga8 = Item.create!(name: "Kuroko no Basuke v.1 (Kuroko's Basketball)", type_tag: "manga", description: "An up-and-coming power player, Taiga Kagami, is just back from America. When he comes to Seirin High School, he meets the super-ordinary boy, Tetsuya Kuroko. Kagami is shocked to find that Kuroko isn't good at basketball, in fact, he's bad! And he's so plain that he's impossible to see.", availability: true, price: 14.99)
manga8.photo.attach(io: File.open("/Users/johnangcla/Desktop/animezon_imgages/kuroko-manga.jpeg"), filename: 'kuroko-manga.jpeg')

manga1 = Item.create!(name: "Naruto v.70 (Naruto and the Sage of Six Paths…!!)", type_tag: "manga", description: "Launching his attack on Madara, Guy's Evening Elephant sends the Uchiha plummeting to the ground, leaving a deep crater in its wake. Guy, however, stops right after the first punch due to the pain, but soon grows accustomed to the pain and restarts the attack. ", availability: true, price: 24.99)
manga1.photo.attach(io: File.open("/Users/johnangcla/Desktop/animezon_imgages/naruto-manga.jpeg"), filename: 'naruto-manga.jpeg')
